### ISSUE TITLE
How to catch exception messages

### ISSUE THREAD

**Issue by SWarnberg** [HelloKitty/TypeSafe.Http.Net#4]
Hi,
I just migrated from Refit to this library because of the excellent support of different serializers. But I have a question regarding exception handling when using this library.  
In Refit you could catch the Refit.ApiException and get the custom error message, sent in the response, in the Content property of that object. In TypeSafe.Http, it seems that all I get is this, where the code is in clear text and the content is not available.

```
System.InvalidOperationException
  HResult=0x80131509
  Message=Request failed with Code: InternalServerError with Context: TypeSafe.Http.Net.HttpRequestContext.
```

So, is there any other way to get detailed exception information?

**Comment by HelloKitty** [comment]
Hi! That was one of the main reasons I wrote this library. To support more serializers, more client implementations and eventually to support both dynamic and compiled clients.

I must warn you though that performance optimizations have not been done. A lot of stuff that could be precomputed and cached is not yet, been busy with other libraries. So just to warn you refit may run faster!

As for catching exceptions, let me take a look. It has been awhile. I do remember I added the ability to suppress exceptions on error HTTP codes but that was under the assumption that you were still getting some valid data back. Let me look it over real quick.

**Comment by HelloKitty** [comment]
Ok, so I may have something implemented already that can serve your needs. There is an attribute called [SupressResponseErrorCodes(...)] which allows you to prevent exceptions from being thrown at all from HTTP error codes being received. So, it will go about deserializing the body/content by the provided Content-Type like normal. So you can read your error that way, maybe.

Is that what you mean?

**Comment by HelloKitty** [comment]
Here is what I'm referring to: https://github.com/HelloKitty/TypeSafe.Http.Net/blob/master/tests/TypeSafe.Http.Net.Performance.NetFramework.Tests/Program.cs#L52

However this assumes that you're sending back some error message or details in the content that can be read even though the HTTP response code was an error. Let me look at what Refit is doing, let me know if the supress attribute is what you were looking for though.

**Comment by HelloKitty** [comment]
The reason I cannot just throw an exception that contains all the response and request, for debugging or logging purposes, is because TypeSafe.HTTP.Net wasn't built with the expectation that only a single client was going to be used. It supports multiple clients. Right now supporting the .NET HttpClient and a popular HTTP library called RestSharp.

I'm going to see what I can do to make the default behavior better though right now.

**Comment by SWarnberg** [comment]
Thanks for the quick response.  
No, it's not really what I want. First off, I think that proper exception handling should be done in a try..catch block. Second, the http code is not returned if I use this attribute, which makes it very hard to distinguish a proper return value and an error, if the service/action returns a string.

**Comment by HelloKitty** [comment]
I agree, there is a lot that needs to be done internally in the library. The initial focus on been on the API and making it extensible. I'm working right now on a solution to throw an exception that contains information about the request and the response now. I'll get it published ASAP.

**Comment by HelloKitty** [comment]
Ok, I threw together a quick and dirty exception Type real quick. It's implemented for the .NET HttpClient and partially for the RestSharp client. More can do done later too I'm sure. Like I said, lots needs to be done internally for this library. Hopefully you find the exterior good though!

So catch this exception [FailedHttpRequestException](https://github.com/HelloKitty/TypeSafe.Http.Net/blob/681fc7c55314419d2a22a3cdb988b19994911690/src/TypeSafe.Http.Net.Api/Exception/FailedHttpRequestException.cs) which should expose some information that you desire. I haven't had the chance to test this. I was just about to go to sleep when I saw this issue's email. I hope this works and hopefully meets your needs. I'll push it up onto NuGet shortly.

**edit:** It will be version 2.2.11

**Comment by HelloKitty** [comment]
I have to sleep now but if you have any feedback on this let me know, it should be propagated to NuGet very shortly. There is a lot I'd like to do with this library at some point when I get some free time. For now I'm happy to implement critical stuff like this and features you need. Let me know.

**Comment by SWarnberg** [comment]
Thanks, I will test it when it gets available. Have a good sleep :-)
Sounds good that you're actively working on this library. Refit seems to be RESTing...

**Comment by SWarnberg** [comment]
Hi,
I just tested it, and it suits my needs. Works good. The only thing I could which for is a string property that returns the response content. Now I need to read it from the stream manually. On the other hand, that property may give overhead for consumers that are not interested in it.

**Comment by HelloKitty** [comment]
Hmmm, I thought about exposing the body content but it required some more work to expose both the string and byte version. Right now everything is either lazy or grabbed directly from the response themselves when needed. So there isn't an overhead in providing access to it. Just was in a huge rush to get it out since you needed it and I had to sleep.

Also, I'd not say I'm actively working on the library. It currently serves my needs when I do use it and if it doesn't I update it. I work on too many projects and libraries to work on this full time but if more than two people used this library I likely would, lots could be done but I'm thankful that just a week's work turned out to produce a working library that is extendible AND has a decent API I think.
